import type { Metadata } from 'next';
import AIVideoContent from './AIVideoContent';

export const metadata: Metadata = {
  title: 'AI Video Production — Marketing Videos Without Cameras | Flowi',
  description:
    'Professional AI-generated marketing videos, product demos, explainers, and social ads. No camera, studio, or crew needed. Delivered in 24-48 hours. From KES 15,000.',
  alternates: {
    canonical: 'https://useflowi.app/services/ai-video',
  },
  openGraph: {
    title: 'AI Video Production — No Camera Needed | Flowi',
    description:
      'Professional marketing videos generated by AI. Product demos, social ads, explainers. 10x cheaper than traditional video. Delivered in days.',
    url: 'https://useflowi.app/services/ai-video',
  },
  keywords: [
    'AI video production Kenya',
    'AI marketing video',
    'AI video generator',
    'product demo video Kenya',
    'social media video production',
    'explainer video Kenya',
    'TikTok video production',
    'AI spokesperson video',
  ],
};

const videoServiceSchema = {
  '@context': 'https://schema.org',
  '@type': 'Service',
  name: 'AI Video Production',
  provider: {
    '@type': 'Organization',
    name: 'Flowi',
    url: 'https://useflowi.app',
  },
  description:
    'AI-generated marketing videos with realistic spokespersons, product demos, and social content. Professional quality, delivered in days.',
  areaServed: 'Kenya',
  serviceType: 'AI Video Production',
  offers: [
    {
      '@type': 'Offer',
      name: 'Single Video',
      price: '15000',
      priceCurrency: 'KES',
      description: '1 AI video up to 60 seconds with professional AI spokesperson',
    },
    {
      '@type': 'Offer',
      name: 'Starter Pack',
      price: '50000',
      priceCurrency: 'KES',
      description: '5 AI videos with multiple presenters and branded intros',
    },
    {
      '@type': 'Offer',
      name: 'Business Pack',
      price: '120000',
      priceCurrency: 'KES',
      description: '15 AI videos with full content strategy and social media calendar',
    },
  ],
};

export default function AIVideoPage() {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(videoServiceSchema) }}
      />
      <AIVideoContent />
    </>
  );
}
